Dev
danielermal/algososh pull request #6
Opened 2022-09-13 12:43 UTC by danielermal

2022-09-13 15:44 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа!🔥

**Вы молодцы!**

**Но есть несколько замечаний, которые нужно исправить:**

- В коде очень много дублирования кода, а также больших условий, проверьте еще раз, и где это возможно вынести дублирующийся код и большие условия в отдельные функции.

- В коде должны отсутствовать магические значения, т.е все ограничения, тайминги и т.д, должны быть вынесены в константы;

- Функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, должны быть вынесены в отдельные файлы utils.ts в папке соответствующего компонента;

- Классы, описывающие работу структур данных, должны быть вынесены в отдельные файлы, в папке соответствующего компонента.

- В файле list-page.js очень много всего. Лучше вынести в отдельные файлы: типы, некоторые функции, объекты.

- В файле sorting-page.js очень много всего. Лучше вынести в отдельные файлы: типы, некоторые функции, объекты.

- Нужно переименовать класс Node в LinkedListNode, для страницы «Связанный список».

- Нужно очистить компонент App от лишних файлов, которые остались при инициализации create-react-app.

- В классе Queue должны быть дополнительные методы для получения данных, например, геттеры isEmpty, elements, head и tail

- Также на странице "Связанный Список" когда пытаешься удалить элемент по индексу, то внизу отображается предыдущий элемент, а не текущий.

![image](https://user-images.githubusercontent.com/70164458/189946437-8da649d2-2fdb-4903-bea5-d2d27fdb2c96.png)


**_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-09-13 15:44 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          disabled={!(value > 0 && value <= 19)}
**Надо исправить:**: Здесь и далее. Лучше магические числа 0 и 19, вынести в отдельные константы.

2022-09-13 15:44 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  };
**Надо исправить**:  По заданию должна быть реализована функция getFibonacciNumbers, которая принимает количество чисел как параметр и возвращает требуемый массив чисел последовательности Фибоначчи; И она должна выполнять только 1 действие. Т.е setFibArr и т.п, в ней лучше не делать.

Можно вынести эту функцию в отдельный файл  utils, в этой же папке.

2022-09-13 15:44 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          return <Circle letter={item + ""} key={index} index={index} />;
**Можно лучше:** Для того чтобы число превратить в строку, есть прекрасный метод `toString()`.
Подробнее: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number/toString

2022-09-13 15:44 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    }
**Надо исправить:** Лучше вынести в отдельную переменную, например: `initialButtonsState`

2022-09-13 15:44 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    })
**Надо исправить:** Здесь и далее, лучше делать это таким образом: 
```js 
setState(prevState => ({...prevState, foo: { ... } }))
```
Это очень много места сэкономит в коде.

2022-09-13 15:44 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    }, 1000);
**Надо исправить:** Повторяющуюся логику, лучше вынести в отдельную функцию.

2022-09-13 15:44 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +              head={item.up ? item.up : index === 0 ? "head" : ""}
**Можно лучше**: Можно записать еще короче, с использованием логического или "||".
Подробнее: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Logical_OR

2022-09-13 15:44 UTC, ArslanMustafin commented on src/components/queue-page/queue-page.tsx
> +  let queue = React.useMemo(() => {
**Надо исправить**: Если переменная не перезаписывается, то её следует объявлять как `const`, обратите внимание, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а изменяют только их внутреннее состояние, поэтому их так же нужно объявлять как `const`

2022-09-13 15:44 UTC, ArslanMustafin commented on src/components/queue-page/queue-page.tsx
> +  }, [newStack]);
**Надо исправить:**: Лучше убрать newStack из зависимостей, т.к функция внутри useMemo от него не зависит.

2022-09-13 15:44 UTC, ArslanDev666 commented on src/constants/data-structures.ts
> +      if (index == 0) {
**Можно лучше**: Лучше всегда использовать строгое сравнение `===` и строгое неравенство `!==`, это избавит от некоторых неявных ошибок связанных с приведением типов (например при использовании нестрогого сравнения выражение `0 == ""` вернет `true`, что не всегда ожидаемо, а выражение `0 === ""` вернет `false` т.к. типы у значений слева и справа разные, слева тип `number`, а справа тип `string`)

2022-09-13 15:44 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +}
**Надо исправить**: Интерфейс лучше вынести в отдельный файл, например types.ts.

2022-09-13 15:44 UTC, ArslanMustafin commented on src/components/sorting-page/sorting-page.tsx
> +}
**Надо исправить:** Как и ранее писалось (в файле list-page.tsx) интерфейс лучше вынести в отдельный файл, например types.ts.

2022-09-13 15:44 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +    }
**Надо исправить**: Здесь и далее. Лучше не злоупотреблять вложенными if-ами. Попробуйте упростить их. 
Например в данном случае можно избавиться как минимум от 1 вложенного if.
```js 
if (bubble) return;

//...
```

2022-09-13 15:44 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +  }, [newStack]);
**Надо исправить:** Если переменная не перезаписывается, то её следует объявлять как const, обратите внимание, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а изменяют только их внутреннее состояние, поэтому их так же нужно объявлять как const. 

Также подумайте, действительно ли тут нужно useMemo, возможно проще будет реализовать это через useRef).

2022-09-13 15:44 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +import React, { useMemo, useRef } from "react";
**Надо исправить:** Перед отправкой задания, убедитесь что весь неиспользуемый код был удалён.

2022-09-13 15:44 UTC, ArslanMustafin commented on src/constants/data-structures.ts
> +    }
**Можно лучше**: Можно воспользоваться тернарным оператором.

2022-09-13 15:44 UTC, ArslanDev666 commented on src/constants/data-structures.ts
> +    }
**Можно лучше:** При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен	не будет:
```
	if (someCondition) {
		return value;
	}
	return data;
```
Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2022-09-13 15:44 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +                : ElementStates.Modified
**Надо исправить:**: Стоит вынести это в отдельную функцию, и попробовать оптимизировать условия.

2022-09-15 09:39 UTC, danielermal commented on src/components/queue-page/queue-page.tsx
> +  }, [newStack]);
При нажатии на кнопку очистить, изменяется состояние у newStack, тем самым создается новая очередь. Если убрать зависимость, то ничего работать не будет

2022-09-15 22:09 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

**Почти все замечания с прошлого ревью были исправлены.**

**Но есть несколько замечаний, которые нужно исправить:**

- Во многих файлах 'магические' значение не вынесены в константы. Нужно это исправить.

  "Магические" значения это - такие значения в коде, смысл которых понятен только написавшему их программисту. Например, иногда в интернет-магазинах цену товара автоматически умножают на 1.2, вместо того чтобы ввести понятную переменную для НДС. И без комментариев такие коэффициенты понять очень сложно.

- По чек-листу в классе Queue нужно реализовать методы: enqueue, dequeue, clear. Вот метода clear вам и не хватает.

- По чек-листу в классе Stack нужно реализовать методы: push, pop, clear. Вот метода clear вам и не хватает.

- По чек-листу в классе LinkedList нужно реализовать методы: prepend, append, addByIndex, deleteByIndex, deleteHead, deleteTail и toArray. Некоторых методов у вас не хватает, а именно: prepend, addByIndex, deleteByIndex, deleteTail и toArray. Я еще уточню этот момент, может быть не придется добавлять эти методы, т.к функционал у вас рабочий.

- Еще раз обращу ваше внимание, классы, описывающие работу структур данных, в вашем случае это все классы в `data-structures.ts`, должны быть вынесены в отдельные файлы в папке соответствующего компонента.

**Места, в которых можно улучшить проект:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- Некоторые методы компонентов обозначены через стрелочные функции, некоторые через ключевое слово function.Руководствуясь принципом единообразия, оптимальнее использовать какой то один подход. Стрелочные функции для объявления функций в компонентах выглядят более лаконично. Более подробно о типах функций в JS: https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Functions

- В некоторых местах нарушено форматирование кода, проблемы с отступами, это затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил что иконки выполнены как компоненты, не могу сказать что это неправильно, но и без причины этого делать не стоит, если вы хотите использовать svg элементы инлайново, для этого можно импортировать их в качестве ReactComponent: https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs.

**_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const maxValue = 19
**Надо исправить**

Имена констант принято записывать в стиле UPPER_CASE. 
Также их стоит вынести за пределы функции, чтобы они не создавались каждый раз при ререндере.
А еще лучше вынести константы в другой файл, с названием например consts, или utils.

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    let t = 0
**Надо исправить:** тут t не используется, поэтому лучше удалить эту переменную.

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          max={19}
**Надо исправить:** Тут тоже лучше заменить на константу, которую вы вывели,

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +          disabled={!(value >= minValue && value <= maxValue)}
**Можно лучше:** Тут лучше чуть чуть по другому написать условие:
``` js 
value < minValue || value > maxValue
```
Сразу ведь чувствуется разница, этот код легче воспринимается, ну и мы сделали условие короче, убрав отрицание.

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/fibonacci-page/fibonacci-page.tsx
> +      }, 500)
**Надо исправить:** Тайминг **(500)** тоже является "магическим" значением, поэтому его нужно вынести в отдельную константу, как и другие магические значения.

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    };
**Надо исправить:** Здесь и далее. Лучше не изменять таким образом состояние `state`. Для этого есть `setState`.
Подробнее почему так делать не желательно: https://stackoverflow.com/questions/37755997/why-cant-i-directly-modify-a-components-state%20-really

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    } else {
**Можно лучше:** При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен	не будет:
```
	if (someCondition) {
		return value;
	}
	return data;
```
Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +            }
**Можно лучше:** Лучше написать с использованием тернарного оператора.
```js
arr.push(state[i] !== j ? j : item);
```

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +    } else {
**Можно лучше:** При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен	не будет:
```
	if (someCondition) {
		return value;
	}
	return data;
```
Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +              }
**Можно лучше:** Лучше написать с использованием тернарного оператора.
```js
arr.push(state[i] !== j ? j : item);
```

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/list-page/list-page.tsx
> +                index === color.index && color.color
**Можно лучше**: Лучше не допускать в коде "тавтологии", стейт color можно назвать например colorState. Это даст понимание, что это за объект.

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/queue-page/queue-page.tsx
> +  }, [newStack]);
В данном случае можно описать бизнес логику без дополнительного флага.
По чек-листу в классе `Queue` нужно реализовать методы: `enqueue, dequeue, clear`.
Вот метода `clear` вам и не хватает. И было бы вообще хорошо, добавить в класс `Queue` геттер, `elements`, который возвращает массив `container`. И тогда  мы будем манипулировать только объектом класса, без лишних посредников, в виде доп. переменных.

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/sorting-page/sorting-page.tsx
> +      }
**Можно лучше:** Здесь и далее. 2 if-а можно объединить в 1, с помощью &&.
Подробнее про логическое "И": https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Logical_AND

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/sorting-page/sorting-page.tsx
> +    let t = 500 * arr.length;
**Надо исправить:** 500 - это магическое число, его требуется вывести в отдельную константу.

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/sorting-page/sorting-page.tsx
> +    let t = 500 * arr.length;
**Надо исправить:** Здесь и далее. 500 - это магическое значение, его требуется вывести в отдельную константу.

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/sorting-page/sorting-page.tsx
> +      }, 500);
**Надо исправить:** 500 - это магическое значение, его требуется вывести в отдельную константу.

2022-09-15 22:09 UTC, ArslanMustafin commented on src/components/stack-page/stack-page.tsx
> +  }, [newStack]);
Подробнее про оптимизацию логики можно посмотреть в комментарии, к файлу `queue-page.tsx`. Тут похожая ситуация.

2022-09-16 19:17 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания были исправлены!🔥

**Работа была не простая, но вы справились. Вы молодцы!**

2022-09-16 19:17 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +    setState((prevState) => [...arr]);
**Можно лучше:** Можно просто написать `setState(arr);` т.к мы не используем предыдущие значения, мы можем написать просто `setState(arr)`, Также, переменная `arr` является массивом, поэтому, раскрывать её, не нужно.

2022-09-16 19:17 UTC, ArslanDev666 commented on src/components/list-page/utils.ts
> +export class LinkedList<T> implements ILinkedList<T> {
**Можно  лучше:** Лучше также реализовать метод `deleteTail`,

2022-09-17 04:23 UTC, merged